/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include <stdint.h>
#include <string.h>
#include "stm32f407xx.h"
#include "stm32f407xx_gpio_driver.h"



void delay(){
	for (uint32_t i = 0; i<500000/2; i++){

	}
}

void EXTI0_IRQHandler(){
	delay();
	GPIO_IRQHandling(GPIO_PIN_NO_0);
	GPIO_TogglePin(GPIOD,GPIO_PIN_NO_12);
}

int main(void)
{
	GPIO_Handle_t GPIOLed;
	memset(&GPIOLed, 0 , sizeof(GPIOLed));
	GPIOLed.pGPIOx = GPIOD;
	GPIOLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;
	GPIOLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	GPIOLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_OP_HIGH_SPEED;
	GPIOLed.GPIO_PinConfig.GPIO_PinOType = GPIO_OP_TYPE_PP;
	GPIOLed.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	GPIO_Handle_t GPIOBtn;
	memset(&GPIOBtn, 0 , sizeof(GPIOBtn));
	GPIOBtn.pGPIOx = GPIOA;
	GPIOBtn.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_0;
	GPIOBtn.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IT_RT;
	GPIOBtn.GPIO_PinConfig.GPIO_PinSpeed = GPIO_OP_HIGH_SPEED;
	//GPIOLed.GPIO_PinConfig.GPIO_PinOType = GPIO_OP_TYPE_PP;
	GPIOBtn.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	GPIO_ClockControl(GPIOD , ENABLE);
	GPIO_ClockControl(GPIOA , ENABLE);
	GPIO_Init(&GPIOLed);
	GPIO_Init(&GPIOBtn);

	GPIO_IRQPriorityConfig(EXTI_NO_0, NVIC_PRIO_15);
	GPIO_IRQInterruptConfig(EXTI_NO_0 , ENABLE);
    /* Loop forever */
	while(1){

	}

	return 0;
}
